INSERT INTO nha_xuat_ban (ma_nxb, ten_nxb) VALUES
(1, 'NXB Trẻ'),
(2, 'NXB Tổng hợp TP.HCM'),
(3, 'NXB Kim Đồng'),
(4, 'NXB Phụ Nữ'),
(5, 'NXB Lao Động'),
(6, 'NXB Thanh Niên'),
(7, 'NXB Thế Giới'),
(8, 'NXB Văn Học'),
(9, 'NXB Dân Trí'),
(10, 'NXB Chính Trị Quốc Gia'),
(11, 'NXB Giáo Dục Việt Nam'),
(12, 'NXB Văn Hóa – Văn Nghệ'),
(13, 'NXB Hồng Đức'),
(14, 'NXB Thái Hà'),
(15, 'Saigon Books'),
(16, 'NXB Cambridge University Press'),
(17, 'NXB Pearson Education'),
(18, 'NXB First News – Trí Việt');
